# *****************************
# Hollistic 
# *****************************

random_state: 42


# *****************************
# Data Upload & Ingestion
# *****************************

suite_name : "dev_raw_suite"
group_name : "dev_raw_data"  # used for upload and ingestion
description: "Contains the raw data upload parameters for the dev environment"

# NOTE: make sure everything is lowercase (hopsworks requirement)
feature_descriptions:
  - name: encounter_id
    description: Unique identifier for each encounter
  - name: patient_nbr
    description: Unique identifier for each patient
  - name: race
    description: Race of the patient
  - name: gender
    description: Gender of the patient
  - name: age
    description: Age group of the patient
  - name: weight
    description: Weight of the patient
  - name: admission_type_id
    description: Identifier for the type of admission
  - name: discharge_disposition_id
    description: Identifier for the discharge disposition
  - name: admission_source_id
    description: Identifier for the source of admission
  - name: time_in_hospital
    description: Number of days the patient was in the hospital
  - name: payer_code
    description: Code for the payer of the hospital bill
  - name: medical_specialty
    description: Medical specialty of the admitting physician
  - name: num_lab_procedures
    description: Number of lab procedures performed
  - name: num_procedures
    description: Number of procedures performed
  - name: num_medications
    description: Number of medications prescribed
  - name: number_outpatient
    description: Number of outpatient visits
  - name: number_emergency
    description: Number of emergency visits
  - name: number_inpatient
    description: Number of inpatient visits
  - name: diag_1
    description: Primary diagnosis code
  - name: diag_2
    description: Secondary diagnosis code
  - name: diag_3
    description: Tertiary diagnosis code
  - name: number_diagnoses
    description: Number of diagnoses
  - name: max_glu_serum
    description: Maximum glucose serum level
  - name: a1cresult
    description: Result of A1C test
  - name: change
    description: Indicates if there was a change in medication
  - name: diabetesmed
    description: Indicates if diabetes medication was given
  - name: readmitted
    description: Readmission status


# *****************************
# Data Split
# *****************************

target_label: "readmitted"
set_sizes: [0.6, 0.2, 0.2]  # need to use list otherwise using "()" will assume it's a string
stratify: True


# *****************************
# Feature Selection
# *****************************

# can be "rfe", "tree" or "all" or "manual"
# if "manual" then specify the features in the list below
# if "rfe" or "tree" then specify the model parameters below
feature_selection: "all"
manual_features: []

# for RFE
fs_model_params:
  n_estimators: 100
  max_depth: 6
  max_features: 20
  random_state: 42

# fs_model_params:
#   n_estimators: 100
#   max_depth: 6
#   max_features: 20
#   random_state: 42
#   criterion: "gini"
#   splitter: "best"
#   min_samples_split: 2
#   min_samples_leaf: 1
#   random_state: 42
#   max_leaf_nodes: None
#   class_weight: None

n_features: 12


# *****************************
# Model Selection
# *****************************

n_trials: 1 


# *****************************
# Explainability
# *****************************

# todo...

# *****************************
# Data Drift
# *****************************

# adding here because Kedro does not support "html" datasets
data_drift_output_path: "data/dev/09_reporting/data_drift_analysis.html"

